### ISSUE TITLE
Documentar trabajos relacionados

### ISSUE THREAD

**Issue by DieegoPeri** [MiguelDHernando/GESPRO_PracticaGestionTareas_1718#12]

**Comment by DieegoPeri** [comment]
Esbozo inicial realizado: https://github.com/davidmigloz/go-bees/wiki/6_TrabajosRelacionados

**Comment by DieegoPeri** [comment]
Esbozo inicial realizado: https://github.com/davidmigloz/go-bees/wiki/6_TrabajosRelacionados

**Comment by lca0037** [comment]
Trabajos documentados
