### ISSUE TITLE
Configurar OpenCV en Android Studio

### ISSUE THREAD

**Issue by RubenMarcosUBU** [MiguelDHernando/GESPRO_PracticaGestionTareas_1718#15]
http://opencv.org/platforms/android.html
http://docs.opencv.org/2.4/doc/tutorials/introduction/android_binary_package/O4A_SDK.html
http://stackoverflow.com/questions/27406303/opencv-in-android-studio

**Comment by hca0004** [comment]
Vale está configurado correctamente.
