### ISSUE TITLE
Investigar Detección de bordes

### ISSUE THREAD

**Issue by MiguelDHernando** [MiguelDHernando/GESPRO_PracticaGestionTareas_1718#19]

**Comment by MiguelDHernando** [comment]
[Tutorial](http://www.bogotobogo.com/python/OpenCV_Python/python_opencv3_Image_Gradient_Sobel_Laplacian_Derivatives_Edge_Detection.php)

**Comment by MiguelDHernando** [comment]
La extracción de contornos provee resultados suficientemente buenos. No es necesario detectar los bordes primero.

**Comment by hca0004** [comment]
Vale está listo.
