### ISSUE TITLE
Elegir herramienta de comunicación

### ISSUE THREAD

**Issue by MiguelDHernando** [MiguelDHernando/GESPRO_PracticaGestionTareas_1718#3]

**Comment by MiguelDHernando** [comment]
Herramientas consideradas: Email, Discord, Telegram, Slack.

Herramientas elegidas: Telegram.

Telegram es una aplicación de mensajería y envío de archivos bastante versátil y simple, se ha elegido por la simplicidad del proyecto y la familiaridad de los integrantes con esta herramienta.

**Comment by MiguelDHernando** [comment]
Herramientas consideradas: Email, Discord, Telegram, Slack.

**Comment by MiguelDHernando** [comment]
Voto por Telegram por su versatilidad y facilidad de uso.

**Comment by hca0004** [comment]
Si optamos por una herramienta de texto como telegram hay que tener en cuenta que no todos la tenemos otra opción podría ser WhatsApp.

**Comment by RubenMarcosUBU** [comment]
La mejor opción sería discord ya que nos permite llamadas compariendo pantalla, chat en tiempo real y además tiene aplicación android
