### ISSUE TITLE
Integrar codeclimate

### ISSUE THREAD

**Issue by DieegoPeri** [MiguelDHernando/GESPRO_PracticaGestionTareas_1718#32]
https://codeclimate.com/

**Comment by DieegoPeri** [comment]
Integrado. Motores de chequeo:

- [checkstyle](https://docs.codeclimate.com/docs/checkstyle)
- [fixme](https://docs.codeclimate.com/docs/fixme)
- [markdownlint](https://docs.codeclimate.com/docs/markdownlint)
- [pmd](https://docs.codeclimate.com/docs/pmd)

**Comment by lca0037** [comment]
Codeclimate integrado
