### ISSUE TITLE
Leer video desde archivo en la app

### ISSUE THREAD

**Issue by lca0037** [MiguelDHernando/GESPRO_PracticaGestionTareas_1718#41]
Añadir a la app la opción de seleccionar si se quiere abrir la cámara o tomar como entrada un archivo de video,

**Comment by lca0037** [comment]
Abandonamos esta opción. Para agilizar el desarrollo de los algoritmos de visión artificial vamos a desarrollar una aplicación en Java en donde si está soportada la opción de leer un archivo de vídeo. El portar los algoritmos posteriormente a Android tomando como entrada la cámara debería ser una tarea trivial.

**Comment by hca0004** [comment]
Vale, video leído.
