### ISSUE TITLE
Elegir herramientas de documentación

### ISSUE THREAD

**Issue by hca0004** [MiguelDHernando/GESPRO_PracticaGestionTareas_1718#6]
Opciones:

- [ ] Microsoft Word

- [x] LaTeX

- [x] GitHub Wikis

**Comment by RubenMarcosUBU** [comment]
Me decanto por GitHub Wikis para tenerlo junto al proyecto mas accesible y muy bien organizado por paginas

**Comment by DieegoPeri** [comment]
Considero [LaTeX ](https://www.latex-project.org/)un potente editor para realizar la documentación.

**Comment by hca0004** [comment]
Yo prefiero GitHub wiki está más a mano mientras se realiza el proyecto. Y no se pierde mucho tiempo.
