### ISSUE TITLE
Prototipo inicial de la app

### ISSUE THREAD

**Issue by lca0037** [MiguelDHernando/GESPRO_PracticaGestionTareas_1718#9]

**Comment by lca0037** [comment]
![1](https://user-images.githubusercontent.com/33413592/32715926-6e694e24-c854-11e7-8cfe-5c560802d676.jpg)
![2](https://user-images.githubusercontent.com/33413592/32715928-71c8cb4e-c854-11e7-8fed-a19e83c44a29.jpg)
![3](https://user-images.githubusercontent.com/33413592/32715937-742482a2-c854-11e7-9a5c-b6719354ae76.jpg)
![4](https://user-images.githubusercontent.com/33413592/32715941-764455f8-c854-11e7-994d-202d2dbcdc90.jpg)
![5](https://user-images.githubusercontent.com/33413592/32715949-7968b7ec-c854-11e7-97e4-a590e4cbf561.jpg)

**Comment by hca0004** [comment]
Esta muy bien.
